student.no=100
student.addr=\uC624\uB9AC
student.name=yejin
student.phone=333-4444

job=student

user.id=0
user.addr=\uC624\uB9AC
user.uname=\uC7A5\uD76C\uC815 
user.phone=222-3333
product.pname=\uC0C8\uC6B0\uAE61
product.price=4000
product.pno=10
order.orderId=10
order.message=\uC8FC\uBB38\uD558\uC168\uC2B5\uB2C8\uB2E4.